---
- hosts: postgres
  become: true
  vars_files:
    - inventories/production/group_vars/vault.yml

  roles:
    - postgres

# - name: Jenkins server
#   hosts: jenkins
#   become: true

#   roles:
#     - jenkins