kube-prometheus-stack:

  grafana:
    admin:
      existingSecret: grafana-admin-secret
      userKey: admin-user
      passwordKey: admin-password

    service:
      type: LoadBalancer



  alertmanager:
    service:
      type: ClusterIP  prometheus:
    service:
      type: ClusterIP

    prometheusSpec:

      additionalScrapeConfigs:

        - job_name: "bastion"

          static_configs:
            - targets:
              - "10.3.0.13:9100"

        - job_name: "postgres"

          static_configs:
            - targets:
              - "10.1.0.11:9187"