# ansible/inventory.yml
all:
  children:
    database:
      hosts:
        postgres-master:
          ansible_host: <private_ip_master>
        postgres-replica:
          ansible_host: <private_ip_replica>
      vars:
        postgresql_version: 14
        replication_user: replicator
        replication_password: "{{ vault_replication_password }}"