apiVersion: v1
kind: Service

metadata:
  name: message-service
  namespace: "{{ .Values.namespace }}"

  labels:
    app: message-service
    monitoring: enabled

spec:
  selector:
    app: message-service

  ports:
    - name: http
      port: {{ .Values.messageService.service.port }}
      targetPort: {{ .Values.messageService.service.targetPort }}

  type: ClusterIP