apiVersion: v1
kind: Service

metadata:
  name: message-service
  namespace: "{{ .Values.namespace }}"

  labels:
    monitoring: enabled

spec:
  selector:
    app: message-service

  ports:
    - port: {{ .Values.messageService.service.port }}
      targetPort: {{ .Values.messageService.service.targetPort }}

  type: ClusterIP