apiVersion: v1
kind: Service

metadata:
  name: user-service
  namespace: "{{ .Values.namespace }}"

  labels:
    app: user-service
    monitoring: enabled

spec:
  selector:
    app: user-service

  ports:
    - name: http
      port: {{ .Values.userService.service.port }}
      targetPort: {{ .Values.userService.service.targetPort }}

  type: ClusterIP