apiVersion: v1
kind: Service

metadata:
  name: web-client
  namespace: "{{ .Values.namespace }}"

  labels:
    monitoring: enabled

spec:

  selector:
    app: web-client

  ports:
    - port: {{ .Values.webClient.service.port }}
      targetPort: {{ .Values.webClient.service.targetPort }}

  type: ClusterIP