apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor

metadata:
  name: messenger-services

spec:

  selector:
    matchLabels:
      monitoring: enabled

  endpoints:
    - port: http
      path: /metrics
      interval: 30s

  namespaceSelector:
    matchNames:
      - messenger-ajax